name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run CMake
      run: cmake -Bbuild
    - name: Make
      run: |
        cd build
        make
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu
        path: build/bfi
  macOS:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run CMake
      run: cmake -Bbuild
    - name: Make
      run: |
        cd build
        make
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos
        path: build/bfi
